name: test
on:
  workflow_dispatch:
  watch:
    types: [started]

steps:
  - uses: actions/checkout@v2
  - uses: actions/setup-java@vv1.4.3
    with:
      java-version: '8' # The JDK version to make available on the path.
      java-package: jdk # (jre, jdk, or jdk+fx) - defaults to jdk
      architecture: x64 # (x64 or x86) - defaults to x64
  - run: java -cp java HelloWorld