name: test
on:
  push:
    branches:
      - main
  workflow_dispatch:
  watch:
    types: started

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout codes
        uses: actions/checkout@v2
      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Run the Maven package
        run: mvn -B package --file pom.xml
      - name: run test
      - run: java -jar ./target/My-Java-Actions-1.0.0-SNAPSHOT-jar-with-dependencies.jar